set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc,ghostty:Tc"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 50000
set -sg escape-time 10
set -g focus-events on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

set -g status-position bottom
set -g status-style "bg=default fg=white"
set -g status-left "#[bold] #S "
set -g status-right " %Y-%m-%d %H:%M "
