add_newline = true
command_timeout = 1000

format = """$directory$git_branch$git_status$python$nodejs$rust$golang$cmd_duration
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "dimmed white"
